### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by SpiderParker** [WisdomSky/Cloudflared-web#2]
Hello,

I installed your community app store on my Umbrel Home, then I created a tunnel and put the token in your app.

I created a public hostname for 2 apps with my local IP and port 2100 for Bitcoin Core.

Unfortunately I get the following error : "ERR_CONNECTION_TIMED_OUT"

At the end of the app URL, i get redirected to ":2000/?origin=host&app=bitcoin&path=%2F"

I tried with Bitcoin app and Jackett

**Comment by SpiderParker** [comment]
Yes, it its in HEALTHY.

<img width="319" alt="Capture d'écran 2023-12-05 154723" src="https://github.com/WisdomSky/Cloudflared-web/assets/15092820/849e91bd-5406-4520-8ad2-94ed24333b3c">


Thank you for your reply.

**Comment by WisdomSky** [comment]
Thanks for the response. Seems like your Cloudflare tunnel is just working fine.

Looking back at your original post. It seems this is a configuration issue on the app you're using

> At the end of the app URL, i get redirected to ":2000/?origin=host&app=bitcoin&path=%2F"

When you use cloudflare tunnel, you would have to create a public host name, which will be your new `host` for the app.

So for example, if within your network, you assigned the app to port 2000, it will be accessible via `http://localhost:2000`, but once you are using cloudflare tunnel, you would need to use the public host name in order to access that app. Let's say the hostname I set is `bitcoin.mywebsite.com`, then it would be publicly accessible through `https://bitcoin.mywebsite.com`. So with that, you would also need to configure your app to start using that `host`. But in this case, it seems the app didn't know that you are using a proxy and still proceeded to redirect using the `host:port` format. 

I'm not familiar with Bitcoin Core and how to configure it to change the domain/host, but you might want to reach out to their community/support for that.

**Comment by SpiderParker** [comment]
Hello,

I tried with Umbrel dashboard on port 80 and it works!

I didn't achieved yet to solve the issue with Bitcoin app, Jackett or Ghostfolio but Mempool works fine!
I'm wondering if Umbrel's localhost ports are accurate now that I've seen this Reddit thread.

Thank you very much for the links and your time!
